### ISSUE TITLE
Offline MapBox tiles not displaying

### ISSUE THREAD

**Issue by denelius** [cocoahero/android-gmaps-addons#4]
I've been trying to get our own tiles to display on Android 4.0.3, but have been unable to get anything to display except the blank map with grid lines. We've tested that the file exists and opens without problem, and we have it working perfectly with the `MapBoxOnlineTileProvider`.

Here's the relevant code from the activity:

``` java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_google_map);

        map = ((MapFragment) getFragmentManager().findFragmentById(R.id.map)).getMap();
        map.setMapType(GoogleMap.MAP_TYPE_NONE);

        File tilefile =  new File(Environment.getExternalStorageDirectory(), "/mapapp/mytiles.mbtiles");
        TileProvider provider = new MapBoxOfflineTileProvider(tilefile);

        map.addTileOverlay(new TileOverlayOptions().tileProvider(provider));

        CameraUpdate upd = CameraUpdateFactory.newLatLngZoom(new LatLng(43.2095, -86.116), 16);
        map.moveCamera(upd);        
    }
```

**Comment by Tybion** [comment]
This works in Android Studio 2.2 (MapsActivity.java) using Google Maps template to create a new project ..

```
@Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;

        // Disable Google Maps tiles - else we get these tiles first
        mMap.setMapType(GoogleMap.MAP_TYPE_NONE);

        // Create new TileOverlayOptions instance.
        TileOverlayOptions opts = new TileOverlayOptions();

        // Get a File reference to the MBTiles file.
        File tilefile =  new File(Environment.getExternalStorageDirectory(),
                "/Android/data/com.mydomain.googlemapsapp2/maps/nsw_map.mbtiles");

        // Create an instance of MapBoxOfflineTileProvider.
        MapBoxOfflineTileProvider provider = new MapBoxOfflineTileProvider(tilefile);

        // Set the tile provider on the TileOverlayOptions.
        opts.tileProvider(provider);

        // Add the tile overlay to the map.
        TileOverlay overlay = mMap.addTileOverlay(opts);

        // Add a marker in Sydney and move the camera
        LatLng sydney = new LatLng(-34, 151);
        mMap.addMarker(new MarkerOptions().position(sydney).title("Marker in Sydney"));
        mMap.moveCamera(CameraUpdateFactory.newLatLng(sydney));

        // Sometime later when the map view is destroyed, close the provider.
        // This is important to prevent a leak of the backing SQLiteDatabase.
        //provider.close()
    }
```

**Comment by LamraniOthmane** [comment]
Please i got this error while reading the .mbtiles file, so i could not open the database: 

E/SQLiteLog: (14) os_unix.c:31278: (2) open(/storage/emulated/0/Android/data/com.example.lamrani.mapstest/maps/test.mbtiles) - 
E/SQLiteDatabase: Failed to open database '/storage/emulated/0/Android/data/com.example.lamrani.mapstest/maps/test.mbtiles'.
                  android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                      at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
                      at com.example.lamrani.mapstest.addons.mapbox.MapBoxOfflineTileProvider.<init>(MapBoxOfflineTileProvider.java:38)
                      at com.example.lamrani.mapstest.addons.mapbox.MapBoxOfflineTileProvider.<init>(MapBoxOfflineTileProvider.java:0)
                      at com.example.lamrani.mapstest.MapsActivity.onMapReady(MapsActivity.java:90)

i put the .mbtiles in my local device, 

please i need help

**Comment by fabiomor** [comment]
Lamrani could be a permission issue, did you check if you enabled external storage access in the manifest?

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by LamraniOthmane** [comment]
Tank you so much :D

**Comment by LamraniOthmane** [comment]
That was the right solution, thanks
